// AUTO-GENERATED from brand-bible.json — DO NOT EDIT BY HAND
export const BRAND = {
  slug: 'dania-latina-salon',
  colors: {
    primary: '#E85D75',
    secondary: '#2D1B2E',
    accent: '#F4A259',
    accentSoft: '#FDE8D0',
    bgMain: '#FFFAF5',
    bgAlt: '#FFF0E6',
    bgCard: '#FFFFFF',
    bgDark: '#2D1B2E',
    textHeading: '#2D1B2E',
    textBody: '#4A3540',
    textMuted: '#9B8A92',
    textLight: '#FFFAF5',
    overallTheme: 'light-warm',
  },
  fonts: {
    heading: 'Libre Baskerville',
    headingFallback: 'Georgia, serif',
    headingWeights: [400, 700],
    body: 'Nunito Sans',
    bodyFallback: 'system-ui, sans-serif',
    bodyWeights: [300, 400, 600, 700],
    navWeight: 600,
    navTextTransform: 'uppercase' as const,
    navLetterSpacing: '0.1em',
  },
  spacing: {
    sectionPadding: 'clamp(3rem, 8vw, 6rem)',
    contentMaxWidth: '1200px',
    cardGap: '24px',
    radiusButtons: '50px',
    radiusCards: '16px',
    radiusImages: '16px',
  },
  archetype: 'portfolio-first',
  sectionOrder: ['hero', 'services-preview', 'gallery-teaser', 'testimonials', 'booking-cta', 'contact'],
  voice: {
    tone: 'Warm, joyful, empowering. Dominican cultural pride meets Canadian professionalism.',
    personality: ['welcoming', 'joyful', 'empowering', 'professional', 'culturally-proud'],
    primaryCTA: 'Book Your Glow-Up',
  },
  people: [
    { name: 'Dania Smiley', role: 'Owner', profilePhotoUrl: null, portfolioPhotos: [], bio: 'Owner and lead stylist. Specializes in Dominican hair techniques for all textures.', instagram: 'danialatinadominicansalon', featured: true },
    { name: 'Natalia', role: 'Stylist', profilePhotoUrl: null, portfolioPhotos: [], bio: 'Known for excellent styling work.', instagram: null, featured: true },
  ],
  images: {
    hero: null,
    logo: null,
    gallery: [],
    atmosphere: [],
  },
  demographics: {
    primaryLanguage: 'en',
    secondaryLanguage: 'es',
    neighborhood: 'South Burlington, Walkers Line',
    targetCustomer: 'Dominican and Latin diaspora families + multicultural Burlington residents seeking curly/textured hair specialists',
  },
  business: {
    name: 'Dania Latina Dominican Hair Salon',
    shortName: 'Dania Latina',
    phone: '(905) 465-0007',
    address: '1900 Walkers Line Unit 7, Burlington, ON L7M 4W5',
    hours: {
      monday: '10 AM - 5 PM',
      tuesday: '10 AM - 6 PM',
      wednesday: '10 AM - 6 PM',
      thursday: '10 AM - 6 PM',
      friday: '10 AM - 7 PM',
      saturday: '8:30 AM - 5 PM',
      sunday: 'Closed',
    },
    bookingUrl: 'https://www.vagaro.com/danialatinadominicanhairsaloninc',
    instagram: 'https://www.instagram.com/danialatinadominicansalon/',
    facebook: 'https://www.facebook.com/p/Dania-Latina-Dominican-Hair-Salon-100063635948519/',
  },
} as const;
