// AUTO-GENERATED from brand-bible.json — DO NOT EDIT BY HAND
// Regenerate by re-running Step 3.0

export const BRAND = {
  slug: 'upperside-real-estate',

  colors: {
    primary: '#bba545',
    secondary: '#5c5b5a',
    accent: '#c4b679',
    bgMain: '#ffffff',
    bgAlt: '#f7f7f7',
    bgCard: '#fbfbfb',
    textHeading: '#222222',
    textBody: '#4a4a4a',
    textMuted: '#6b6b6b',
    textLight: '#ffffff',
    border: '#ececeb',
    dark: '#222222',
    gold: '#bba545',
    goldLight: '#c4b679',
    overallTheme: 'light-clean',
  },

  fonts: {
    heading: 'Montserrat',
    headingFallback: 'sans-serif',
    headingWeights: [400, 500, 600, 700, 800],
    body: 'Open Sans',
    bodyFallback: 'sans-serif',
    bodyWeights: [300, 400, 500, 600],
    navWeight: 600,
    navTextTransform: 'uppercase' as const,
    navLetterSpacing: '0.05em',
  },

  spacing: {
    sectionPadding: '80px',
    contentMaxWidth: '1280px',
    cardGap: '24px',
    radiusButtons: '6px',
    radiusCards: '8px',
    radiusImages: '8px',
  },

  archetype: 'service-first',
  sectionOrder: ['hero', 'services', 'agents-preview', 'about', 'testimonials', 'contact'],

  voice: {
    tone: 'professional',
    personality: ['professional', 'trustworthy', 'established', 'knowledgeable', 'approachable'],
    primaryCTA: 'Find Your Dream Home',
  },

  people: [
    {
      name: 'Art Arinkin',
      role: 'Broker',
      profilePhotoUrl: 'https://www.uppersiderealestate.com/files/agent_profile_pics/1714514373.png',
      portfolioPhotos: [],
      bio: 'Knowledgeable Real Estate Broker with 20 years of experience in Commercial and Residential real estate.',
      instagram: null,
      featured: true,
    },
    {
      name: 'Tirdad Gharachorloo',
      role: 'Broker of Record',
      profilePhotoUrl: null,
      portfolioPhotos: [],
      bio: null,
      instagram: null,
      featured: true,
    },
    {
      name: 'Igor Fishman',
      role: 'Broker',
      profilePhotoUrl: null,
      portfolioPhotos: [],
      bio: null,
      instagram: null,
      featured: true,
    },
    {
      name: 'Mike Mayer',
      role: 'Broker',
      profilePhotoUrl: null,
      portfolioPhotos: [],
      bio: null,
      instagram: null,
      featured: false,
    },
  ],

  images: {
    hero: 'https://www.uppersiderealestate.com/themes/bannertheme/lead_formsbg/bg2/calculation.jpg',
    logo: 'https://www.uppersiderealestate.com/files/themeManager/9119/theme24/Surendran_Sam_fl_1.jpg',
    gallery: [
      { url: 'https://storage.googleapis.com/canadian/69cc19b20a7da2e7f58f5e23.jpeg', description: '17 St Anne Way listing' },
      { url: 'https://storage.googleapis.com/canadian/69d17f7e57b9be4d65442c04.jpeg', description: '1 Radley Street listing' },
      { url: 'https://storage.googleapis.com/canadian/69cde1a257b9be4d6543a65a.jpeg', description: '208 Cabernet Road listing' },
    ],
  },

  demographics: {
    primaryLanguage: 'en' as const,
    secondaryLanguage: null,
    neighborhood: 'Vaughan — Bathurst corridor',
    targetCustomer: 'GTA homebuyers and sellers',
  },

  business: {
    name: 'Upperside Real Estate Limited',
    shortName: 'Upperside Real Estate',
    tagline: 'Your Trusted Partner in GTA Real Estate',
    phone: '905-597-9333',
    fax: '905-597-7677',
    address: '5&6-7900 Bathurst Street, Vaughan, ON L4J 0B8',
    city: 'Vaughan',
    email: null,
    instagram: 'https://www.instagram.com/uppersiderealestate/',
    youtube: 'https://www.youtube.com/channel/UCL8McCS1Hs5W4XwjZc7u2ow',
    facebook: 'https://www.facebook.com/artem.arinkin',
    linkedin: 'https://www.linkedin.com/pub/artem-arinkin/18/6aa/4a6',
  },

  agents: [
    { name: 'Art Arinkin', role: 'Broker' },
    { name: 'Tirdad Gharachorloo', role: 'Broker of Record' },
    { name: 'Igor Fishman', role: 'Broker' },
    { name: 'Mike Mayer', role: 'Broker' },
    { name: 'Adrian Kofler', role: 'Sales Representative' },
    { name: 'Afsoon Rezaei', role: 'Sales Representative' },
    { name: 'Alexandra Zadounaeva', role: 'Sales Representative' },
    { name: 'Amir Jamehshouranian', role: 'Sales Representative' },
    { name: 'Asia Geiman', role: 'Sales Representative' },
    { name: 'Bahman Bayat Fard', role: 'Sales Representative' },
    { name: 'Betty Copeland', role: 'Sales Representative' },
    { name: 'Carly Mandel', role: 'Sales Representative' },
    { name: 'David Burtscher', role: 'Sales Representative' },
    { name: 'Eldar Mandil', role: 'Sales Representative' },
    { name: 'Fara Afzail', role: 'Sales Representative' },
    { name: 'Fay Shamshirzan', role: 'Sales Representative' },
    { name: 'Frank Savino', role: 'Sales Representative' },
    { name: 'Helen Basantes', role: 'Sales Representative' },
    { name: 'Hila Baron', role: 'Sales Representative' },
    { name: 'Howard Sheldon Levitt', role: 'Sales Representative' },
    { name: 'Inna Teytelbaum', role: 'Sales Representative' },
    { name: 'Inna Opolinski', role: 'Sales Representative' },
    { name: 'Irina Shapiro', role: 'Sales Representative' },
    { name: 'Jack Florans', role: 'Sales Representative' },
    { name: 'James Migliore', role: 'Sales Representative' },
    { name: 'John McCubbin', role: 'Sales Representative' },
    { name: 'Joshua Chitiz', role: 'Sales Representative' },
    { name: 'Karls Aniscenko', role: 'Sales Representative' },
    { name: 'Leah Gorlicky', role: 'Sales Representative' },
    { name: 'Lorne Spivak', role: 'Sales Representative' },
    { name: 'Ludmila Melekhina', role: 'Sales Representative' },
    { name: 'Madison Wine', role: 'Sales Representative' },
    { name: 'Malca Narrol', role: 'Sales Representative' },
    { name: 'Marco Joneidi', role: 'Sales Representative' },
    { name: 'Maurice Aguayo', role: 'Sales Representative' },
    { name: 'Mehdi Saidi-Yousefi', role: 'Sales Representative' },
    { name: 'Michael Babaev', role: 'Sales Representative' },
    { name: 'Michael MacDougall', role: 'Sales Representative' },
    { name: 'Mily Rom', role: 'Sales Representative' },
    { name: 'Mohammad Radmanesh', role: 'Sales Representative' },
    { name: 'Natalia Birnbaum', role: 'Sales Representative' },
    { name: 'Natalia Lopatine', role: 'Sales Representative' },
    { name: 'Natalia Smirnova', role: 'Sales Representative' },
    { name: 'Natalie Lederman', role: 'Sales Representative' },
    { name: 'Niloufar Meshbahi', role: 'Sales Representative' },
    { name: 'Nissan Peisahov', role: 'Sales Representative' },
    { name: 'Oksana Ilioukevitch', role: 'Sales Representative' },
    { name: 'Oleg Cherepakha', role: 'Sales Representative' },
    { name: 'Oleg Trubyuk', role: 'Sales Representative' },
    { name: 'Olga Kaminskaya', role: 'Sales Representative' },
    { name: 'Peggy Mohammadian', role: 'Sales Representative' },
    { name: 'Peter De Castro', role: 'Sales Representative' },
    { name: 'Priscilla Shirazi', role: 'Sales Representative' },
    { name: 'Raheesa Nazarali', role: 'Sales Representative' },
    { name: 'Riva Kenigsvain', role: 'Sales Representative' },
    { name: 'Ryan Mandel', role: 'Sales Representative' },
    { name: 'Sahar Firoozian', role: 'Sales Representative' },
    { name: 'Sana Kasim', role: 'Sales Representative' },
    { name: 'Sanchita Sood', role: 'Sales Representative' },
    { name: 'Sara Jane Serednicki', role: 'Sales Representative' },
    { name: 'Sharon Rival', role: 'Sales Representative' },
    { name: 'Sima Mary Aryan', role: 'Sales Representative' },
    { name: 'Tara Fallah', role: 'Sales Representative' },
    { name: 'Ted Berlad', role: 'Sales Representative' },
    { name: 'Vida Haje Ghassemi', role: 'Sales Representative' },
    { name: 'Vlad Bretgoltz', role: 'Sales Representative' },
    { name: 'Vladimir Proskurin', role: 'Sales Representative' },
    { name: 'Vsevolod Solomyanik', role: 'Sales Representative' },
    { name: 'Wayne Chorner', role: 'Sales Representative' },
    { name: 'Winnie Cheng', role: 'Sales Representative' },
  ],
} as const;
